### PR TITLE
Smart computer

### PR DESCRIPTION
**Pull request by egorguslyan**
Now I can't beat it. It's too smart.

### CODE REVIEW

**Comment by egorguslyan** [comment]
It counts priority for every piece:
 - **+PieceCost** if the piece in danger
 - **+AveragedPieceCost** of all attackable pieces
 - **-PieceCost * (dangerSquares / allReachableSquares)**
 - **+1** for aggressive pieces, if aggressive computer enabled

Looks simple, but plays harder, because computer won't lose mighty pieces

**Comment by egorguslyan** [comment]
Maybe this pull request can close issue #15

**Comment by CorruptedArk** [comment]
I like these changes so far. The only issue I have is that improved AI appears to completely override aggressive computer, so I think a user should only be able to press one or the other. And maybe the naming should be smart computer and aggressive computer. I can implement the user interface change after I merge this pull request if you don't want to do it.

**Comment by egorguslyan** [comment]
I will try

**Comment by CorruptedArk** [comment]
It looks good now, very good work!

**Pull request merged**
